[package]
name = "nss-aad"
version = "0.2.0"
authors = ["Brandon Matthews <brmatt@microsoft.com>"]


[dependencies]
reqwest = "*"
libc = "0.2.21"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6.2"
serde_json = "0.9"
url = "*"

[lib]
name = "nss_aad"
crate-type = ["cdylib"]

